### ISSUE TITLE
Create Intermediate section

### ISSUE THREAD

**Issue by sabarnac** [sabarnac/shader-tutorial#10]
Create an intermediate section in the navigation section and a placeholder ToC page.

**Comment by sabarnac** [comment]
Includes #11

**Comment by XavierSchiller** [comment]
You probably shouldn't separate these topics, While they are difficult, they do not benefit from being placed under intermediate either.

**Comment by sabarnac** [comment]
These topics don't provide information on the basics of shader programming, so provide no benefit being under basics. These are topics that would be present at a higher than basics level, which is what intermediates is intended for.

**Comment by sabarnac** [comment]
There will also be more topics added to intermediates, and once all the topics are finalized, they may be sub-categorized within intermediates
