### ISSUE TITLE
Add a chapter to provide a brief on the mathematics

### ISSUE THREAD

**Issue by sabarnac** [sabarnac/shader-tutorial#12]
A chapter explaining the necessary mathematics can explain certain details that cannot be provided in other chapters, and act as a primer for certain small concepts that will be used very frequently in other chapters.

**Comment by XavierSchiller** [comment]
What part of math? You're going to have list them a little before anyone can add stuff.

**Comment by sabarnac** [comment]
Well, totally forgot to update here, already written the chapter giving a brief on vector, matrix, and trignometry math in commit 1f6c46ff6c024213a90865a0e13aa3f88f9e9c36

**Comment by sabarnac** [comment]
Content modified with d2ddd78c441e60ba13ffbc7c38a04b6f4acbcdcc

**Comment by XavierSchiller** [comment]
Things I see so far:

- Using Unit Vectors but not pointing them out as unit vectors. Unit Vectors and how they behave is fundamental to any Vector topic. Consider adding them in.

- You provide the details of how Matrix Multiplication is performed with each step, which is longer than it should be, make it smaller. Consider adding in the reason as to why Matrix Multiplication is performed. The subject of Transformations should be brushed upon here.

- Matrices have special meaning. Do not forget to add why a Identity matrix is considered as such. For example, the multiplication of a Identity matrix corresponds to a shift from origin to the origin. May not seem like much, but you're trying to explain concepts in math, and the reason why. Include them as well. 

- I mentioned Transformations. Your Shearing, Scaling and other operations DEPEND on transformations to happen. I highly suggest you give an introductions into what transforms are. This would help readers gain a better understanding of what they are reading.

- Should give a little more detail into that trigonometric section.

**Comment by sabarnac** [comment]
> Using Unit Vectors but not pointing them out as unit vectors. Unit Vectors and how they behave is fundamental to any Vector topic. Consider adding them in.

We don't need to focus or mention unit vectors, since that isn't a focus.. They may be used in certain areas, but knowing about unit vectors is't critical. A later chapter deals with the explanation of unit vectors since it is primarily relevant there

> You provide the details of how Matrix Multiplication is performed with each step, which is longer than it should be, make it smaller. Consider adding in the reason as to why Matrix Multiplication is performed. The subject of Transformations should be brushed upon here.

Will add a basic description of transformations through matrices beforehand, and cut down the multiplication material.

>  Matrices have special meaning. Do not forget to add why a Identity matrix is considered as such. For example, the multiplication of a Identity matrix corresponds to a shift from origin to the origin. May not seem like much, but you're trying to explain concepts in math, and the reason why. Include them as well.

The explanation of the the identity matrix is provided through a comparison to the number one, something that retains the identity of any value multiplied with it.

> I mentioned Transformations. Your Shearing, Scaling and other operations DEPEND on transformations to happen. I highly suggest you give an introductions into what transforms are. This would help readers gain a better understanding of what they are reading.

As said in reply to point 2, adding a basic description of what transformations are.

> Should give a little more detail into that trigonometric section.

Not much more detail can be added about it, except for an example on how the pattern can be used.
